<? php
echo '<!doctype html>';
echo '<html lang="en">';
echo '<head>';
echo '<!-- Required meta tags -->';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">';
echo '<!-- Page Title -->';
echo '<title>JerryDigiGraphixs</title>';
echo '';
echo '<!-- Favicon -->';
echo '<link rel="icon" href="images/favicon.ico">';
echo '<!-- Animate -->';
echo '<link rel="stylesheet" href="css/animate.min.css">';
echo '<!-- Bootstrap CSS -->';
echo '<link rel="stylesheet" href="css/bootstrap.min.css">';
echo '<!-- Font Awesome -->';
echo '<link href="css/all.min.css" rel="stylesheet"> <!--load all styles -->';
echo '<link href="css/all.css" rel="stylesheet"> <!--load all styles -->';
echo '<link rel="stylesheet" href="css/font-awesome.min.css">';
echo '<link rel="stylesheet" href="css/font-awesome.css">';
echo '';
echo '<!-- Owl Carousel -->';
echo '<link rel="stylesheet" href="css/owl.carousel.min.css">';
echo '<link rel="stylesheet" href="css/owl.theme.default.min.css">';
echo '<!-- Cube Portfolio -->';
echo '<link rel="stylesheet" href="css/cubeportfolio.min.css">';
echo '<!-- Fancy Box -->';
echo '<link rel="stylesheet" href="css/jquery.fancybox.min.css">';
echo '<!-- REVOLUTION STYLE SHEETS -->';
echo '<link rel="stylesheet" type="text/css" href="rs-plugin/css/settings.css">';
echo '<link rel="stylesheet" type="text/css" href="rs-plugin/css/navigation.css">';
echo '<!-- Style Sheet -->';
echo '<link rel="stylesheet" href="css/style.css">';
echo '<!--Color Scheme -->';
echo '<link rel="stylesheet" href="css/yellow.css">';
echo '';
echo '</head>';
echo '';
echo '<body data-spy="scroll" data-target=".navbar" data-offset="90">';
echo '';
echo '<!--Loader Start-->';
echo '<div class="loader">';
echo '<div class="loader-inner">';
echo '<div class="loader-blocks">';
echo '<span class="block-1"></span>';
echo '<span class="block-2"></span>';
echo '<span class="block-3"></span>';
echo '<span class="block-4"></span>';
echo '<span class="block-5"></span>';
echo '<span class="block-6"></span>';
echo '<span class="block-7"></span>';
echo '<span class="block-8"></span>';
echo '<span class="block-9"></span>';
echo '<span class="block-10"></span>';
echo '<span class="block-11"></span>';
echo '<span class="block-12"></span>';
echo '<span class="block-13"></span>';
echo '<span class="block-14"></span>';
echo '<span class="block-15"></span>';
echo '<span class="block-16"></span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!--Loader End-->';
echo '';
echo '<!--Header start-->';
echo '<header>';
echo '<!--header top-->';
echo '<div class="top-header-area bg-transparent text-white">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-md-6">';
echo '<div class="header-top-text">Lagos, Nigeria';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6">';
echo '<div class="header-top-text text-right">';
echo '<a href="#." class="text-white mr-3"><i class="fa fa-mobile mr-2"></i>+234 708 992 1915</a>';
echo '<a href="#." class="text-white"><i class="fa fa-comment mr-2"></i>Jdgcr8ive@gmail.com</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<!--Navigation-->';
echo '<nav class="navbar navbar-top-default navbar-expand-lg navbar-gradient gradient-bg1 nav-box-round">';
echo '<div class="container">';
echo '<a href="#home" title="Logo" class="logo scroll">';
echo '<img src="images/logo-bold-white.png" alt="logo" class="logo-dark default">';
echo '</a>';
echo '';
echo '<!--Nav Links-->';
echo '<div class="collapse navbar-collapse" id="wexim">';
echo '<div class="navbar-nav ml-auto">';
echo '<a class="nav-link scroll" href="#home">Home</a>';
echo '<a class="nav-link scroll" href="#about">About</a>';
echo '<!-- <a class="nav-link scroll" href="#team">Team</a> -->';
echo '<a class="nav-link scroll" href="#portfolio">Work</a>';
echo '<!-- <a class="nav-link scroll" href="#price">Pricing</a> -->';
echo '<!-- <a class="nav-link scroll" href="#blog">Blog</a> -->';
echo '<a class="nav-link scroll" href="#contact">Contact</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<!--Side Menu Button-->';
echo '<a href="javascript:void(0)" class="d-inline-block sidemenu_btn" id="sidemenu_toggle">';
echo '<span></span>';
echo '<span></span>';
echo '<span></span>';
echo '</a>';
echo '';
echo '</div>';
echo '</nav>';
echo '';
echo '<!--Side Nav-->';
echo '<div class="side-menu">';
echo '<div class="inner-wrapper">';
echo '<span class="btn-close" id="btn_sideNavClose"><i></i><i></i></span>';
echo '<nav class="side-nav w-100">';
echo '<ul class="navbar-nav">';
echo '<li class="nav-item">';
echo '<a class="nav-link scroll" href="#home">Home</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link scroll" href="#about">About</a>';
echo '</li>';
echo '<!-- <li class="nav-item"> -->';
echo '<!-- <a class="nav-link scroll" href="#team">Team</a> -->';
echo '<!-- </li> -->';
echo '<li class="nav-item">';
echo '<a class="nav-link scroll" href="#portfolio">Work</a>';
echo '</li>';
echo '<!-- <li class="nav-item"> -->';
echo '<!-- <a class="nav-link scroll" href="#price">Pricing</a> -->';
echo '<!-- </li> -->';
echo '<!-- <li class="nav-item"> -->';
echo '<!-- <a class="nav-link scroll" href="#blog">Blog</a> -->';
echo '<!-- </li> -->';
echo '<li class="nav-item">';
echo '<a class="nav-link scroll" href="#contact">Contact</a>';
echo '</li>';
echo '</ul>';
echo '</nav>';
echo '';
echo '<div class="side-footer text-white w-100">';
echo '<ul class="social-icons-simple">';
echo '<li><a class="facebook-text-hvr" href="javascript:void(0)"><i class="fab fa-github"></i> </a> </li>';
echo '<li><a class="instagram-text-hvr" href="javascript:void(0)"><i class="fab fa-instagram"></i> </a> </li>';
echo '<li><a class="twitter-text-hvr" href="javascript:void(0)"><i class="fab fa-twitter"></i> </a> </li>';
echo '</ul>';
echo '<p class="text-white">&copy; 2020 JerryDigiGraphixs. Crafted With 🖤 by AceNetics</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<a id="close_side_menu" href="javascript:void(0);"></a>';
echo '<!-- End side menu -->';
echo '';
echo '';
echo '</header>';
echo '<!--Header end-->';
echo '';
echo '<!--slider-->';
echo '<section id="home" class="p-0 onepage-slide">';
echo '<h2 class="d-none">hidden</h2>';
echo '<div id="rev_slider_19_1_wrapper" class="rev_slider_wrapper fullscreen-container" data-alias="wexim_slider_01" data-source="gallery" style="background:transparent;padding:0px;">';
echo '<!-- START REVOLUTION SLIDER 5.4.8.1 fullscreen mode -->';
echo '<div id="rev_slider_19_1" class="rev_slider fullscreenbanner" style="display:none;" data-version="5.4.8.1">';
echo '<ul>';
echo '<!-- SLIDE  -->';
echo '<li data-index="rs-1" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off"  data-easein="default" data-easeout="default" data-masterspeed="default"  data-thumb="images/slide-img1.jpg"  data-rotate="0" data-description="">';
echo '<!-- MAIN IMAGE -->';
echo '<img src="images/slider-image7.jpg"  alt=""  data-bgposition="center center" data-bgfit="cover" data-bgparallax="10" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>';
echo '<!-- LAYERS -->';
echo '';
echo '<!-- Overlay -->';
echo '<div class="bg-dark bg-overlay opacity-5 z-index-1"></div>';
echo '';
echo '<!-- layer nr. 1 -->';
echo '<div class="tp-caption NotGeneric-SubTitle tp-resizeme text-white"';
echo 'data-x="['left','left','left','left']" data-hoffset="['45','45','20','15']"';
echo 'data-y="['middle','middle','middle','middle']" data-voffset="['-35','-35','-35','-20']"';
echo 'data-fontsize="['44','44','35','30']"';
echo 'data-lineheight="['44','44','35','30']"';
echo 'data-width="none"';
echo 'data-height="none"';
echo 'data-whitespace="nowrap"';
echo 'data-type="text"';
echo 'data-responsive_offset="on"';
echo 'data-frames='[{"from":"y:50px;opacity:0;","speed":1000,"to":"o:1;","delay":600,"ease":"Power4.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[175%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power2.easeInOut"},{"frame":"hover","speed":"300","ease":"Power1.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);bw:2px 2px 2px 2px;"}]'';
echo 'data-textAlign="['left','left','left','left']"';
echo 'style="z-index: 8; white-space: nowrap; font-family:'Poppins', sans-serif; !important; font-weight: 500;">';
echo 'Making your vision come true <br> that is what we do!';
echo '</div>';
echo '<!-- layer nr. 2 -->';
echo '<div class="tp-caption NotGeneric-Title tp-resizeme font-weight-100 text-white"';
echo 'data-x="['left','left','left','left']" data-hoffset="['45','45','20','15']"';
echo 'data-y="['middle','middle','middle','middle']" data-voffset="['55','55','55','55']"';
echo 'data-fontsize="['20','20','18','14']"';
echo 'data-lineheight="['25','25','25','25']"';
echo 'data-width="none"';
echo 'data-height="none"';
echo 'data-whitespace="nowrap"';
echo 'data-type="text"';
echo 'data-responsive_offset="on"';
echo 'data-frames='[{"from":"y:50px;opacity:0;","speed":1000,"to":"o:1;","delay":800,"ease":"Power4.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[175%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power2.easeInOut"},{"frame":"hover","speed":"300","ease":"Power1.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);bw:2px 2px 2px 2px;"}]'';
echo 'data-textAlign="['left','left','left','left']"';
echo 'style="z-index:99; white-space: nowrap;">';
echo 'We offer quality designs and the best project management for <br>your ideas, 100% delivery guaranteed. See for yourself, get on board';
echo '';
echo '</div>';
echo '<!-- layer nr. 3 -->';
echo '<div class="tp-caption z-index-5"';
echo 'data-x="['left','left','left','left']" data-hoffset="['45','45','20','15']"';
echo 'data-y="['middle','middle','middle','middle']" data-voffset="['135','135','135','135']"';
echo 'data-fontsize="['18','18','18','18']"';
echo 'data-lineheight="['18','18','18','18']"';
echo 'data-width="none"';
echo 'data-height="none"';
echo 'data-whitespace="nowrap"';
echo 'data-type="text"';
echo 'data-responsive_offset="on"';
echo 'data-frames='[{"from":"y:50px;opacity:0;","speed":1000,"to":"o:1;","delay":1000,"ease":"Power4.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[175%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power2.easeInOut"},{"frame":"hover","speed":"300","ease":"Power1.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);bw:2px 2px 2px 2px;"}]'';
echo 'data-textAlign="['center','center','center','center']"';
echo 'style="z-index: 7; white-space: nowrap; font-family:'Poppins', sans-serif; !important; font-weight: 100;">';
echo '<a href="#." class="btn btn-gradient btn-rounded btn-large mr-2">Get Started</a>';
echo '<a href="#." class="btn btn btn-white btn-rounded btn-large">learn More</a>';
echo '</div>';
echo '';
echo '</li>';
echo '';
echo '<!-- SLIDE  -->';
echo '<li data-index="rs-2" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off"  data-easein="default" data-easeout="default" data-masterspeed="default"  data-thumb="images/slide-img2.jpg"  data-rotate="0"  data-description="">';
echo '';
echo '<!-- MAIN IMAGE -->';
echo '<img src="images/slider-image8.jpg"  alt=""  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat"  data-bgparallax="10" class="rev-slidebg" data-no-retina>';
echo '<!-- LAYERS -->';
echo '';
echo '<!-- Overlay -->';
echo '<div class="bg-dark bg-overlay opacity-5 z-index-1"></div>';
echo '';
echo '<!-- layer nr. 1 -->';
echo '<div class="tp-caption NotGeneric-SubTitle tp-resizeme text-white"';
echo 'data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']"';
echo 'data-y="['middle','middle','middle','middle']" data-voffset="['-35','-35','-35','-20']"';
echo 'data-fontsize="['44','44','35','30']"';
echo 'data-lineheight="['44','44','35','30']"';
echo 'data-width="none"';
echo 'data-height="none"';
echo 'data-whitespace="nowrap"';
echo 'data-type="text"';
echo 'data-responsive_offset="on"';
echo 'data-frames='[{"from":"y:50px;opacity:0;","speed":1000,"to":"o:1;","delay":600,"ease":"Power4.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[175%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power2.easeInOut"},{"frame":"hover","speed":"300","ease":"Power1.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);bw:2px 2px 2px 2px;"}]'';
echo 'data-textAlign="['center','center','center','center']"';
echo 'style="z-index: 8; white-space: nowrap; font-family:'Poppins', sans-serif; !important; font-weight: 500;">';
echo 'Making your vision come true <br> that is what we do!';
echo '</div>';
echo '<!-- layer nr. 2 -->';
echo '<div class="tp-caption NotGeneric-Title tp-resizeme font-weight-100 text-white"';
echo 'data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']"';
echo 'data-y="['middle','middle','middle','middle']" data-voffset="['55','55','55','55']"';
echo 'data-fontsize="['20','20','18','14']"';
echo 'data-lineheight="['25','25','25','25']"';
echo 'data-width="none"';
echo 'data-height="none"';
echo 'data-whitespace="nowrap"';
echo 'data-type="text"';
echo 'data-responsive_offset="on"';
echo 'data-frames='[{"from":"y:50px;opacity:0;","speed":1000,"to":"o:1;","delay":800,"ease":"Power4.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[175%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power2.easeInOut"},{"frame":"hover","speed":"300","ease":"Power1.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);bw:2px 2px 2px 2px;"}]'';
echo 'data-textAlign="['center','center','center','center']"';
echo 'style="z-index:99; white-space: nowrap;">';
echo 'We offer quality designs and the best project management for <br>your ideas, 100% delivery guaranteed. See for yourself, get on board';
echo '';
echo '</div>';
echo '<!-- layer nr. 3 -->';
echo '<div class="tp-caption z-index-5"';
echo 'data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']"';
echo 'data-y="['middle','middle','middle','middle']" data-voffset="['135','135','135','135']"';
echo 'data-fontsize="['18','18','18','18']"';
echo 'data-lineheight="['18','18','18','18']"';
echo 'data-width="none"';
echo 'data-height="none"';
echo 'data-whitespace="nowrap"';
echo 'data-type="text"';
echo 'data-responsive_offset="on"';
echo 'data-frames='[{"from":"y:50px;opacity:0;","speed":1000,"to":"o:1;","delay":1000,"ease":"Power4.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[175%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power2.easeInOut"},{"frame":"hover","speed":"300","ease":"Power1.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);bw:2px 2px 2px 2px;"}]'';
echo 'data-textAlign="['center','center','center','center']"';
echo 'style="z-index: 7; white-space: nowrap; font-family:'Poppins', sans-serif; !important; font-weight: 100;">';
echo '<a href="#." class="btn btn-gradient btn-rounded btn-large mr-2">Get Started</a>';
echo '<a href="#." class="btn btn btn-white btn-rounded btn-large">learn More</a>';
echo '</div>';
echo '';
echo '</li>';
echo '';
echo '<!-- SLIDE  -->';
echo '<li data-index="rs-3" data-transition="crossfade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off"  data-easein="default" data-easeout="default" data-masterspeed="default"  data-thumb="images/slide-img2.jpg"  data-rotate="0"  data-saveperformance="off"  data-title="Slide" data-param1="" data-description="">';
echo '';
echo '<!-- MAIN IMAGE -->';
echo '<img src="images/slider-image9.jpg"  alt=""  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat"  data-bgparallax="10" class="rev-slidebg" data-no-retina>';
echo '<!-- LAYERS -->';
echo '';
echo '<!-- Overlay -->';
echo '<div class="bg-dark bg-overlay opacity-7 z-index-1"></div>';
echo '';
echo '<!-- layer nr. 1 -->';
echo '<div class="tp-caption NotGeneric-SubTitle tp-resizeme text-white"';
echo 'data-x="['right','right','right','right']" data-hoffset="['45','45','20','15']"';
echo 'data-y="['middle','middle','middle','middle']" data-voffset="['-35','-35','-35','-20']"';
echo 'data-fontsize="['44','44','35','30']"';
echo 'data-lineheight="['44','44','35','30']"';
echo 'data-width="none"';
echo 'data-height="none"';
echo 'data-whitespace="nowrap"';
echo 'data-type="text"';
echo 'data-responsive_offset="on"';
echo 'data-frames='[{"from":"y:50px;opacity:0;","speed":1000,"to":"o:1;","delay":600,"ease":"Power4.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[175%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power2.easeInOut"},{"frame":"hover","speed":"300","ease":"Power1.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);bw:2px 2px 2px 2px;"}]'';
echo 'data-textAlign="['right','right','right','right']"';
echo 'style="z-index: 8; white-space: nowrap; font-family:'Poppins', sans-serif; !important; font-weight: 500;">';
echo 'Making your vision come true <br> that is what we do!';
echo '</div>';
echo '<!-- layer nr. 2 -->';
echo '<div class="tp-caption NotGeneric-Title tp-resizeme font-weight-100 text-white"';
echo 'data-x="['right','right','right','right']" data-hoffset="['45','45','20','15']"';
echo 'data-y="['middle','middle','middle','middle']" data-voffset="['55','55','55','55']"';
echo 'data-fontsize="['20','20','18','14']"';
echo 'data-lineheight="['25','25','25','25']"';
echo 'data-width="none"';
echo 'data-height="none"';
echo 'data-whitespace="nowrap"';
echo 'data-type="text"';
echo 'data-responsive_offset="on"';
echo 'data-frames='[{"from":"y:50px;opacity:0;","speed":1000,"to":"o:1;","delay":800,"ease":"Power4.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[175%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power2.easeInOut"},{"frame":"hover","speed":"300","ease":"Power1.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);bw:2px 2px 2px 2px;"}]'';
echo 'data-textAlign="['right','right','right','right']"';
echo 'style="z-index:99; white-space: nowrap;">';
echo 'We offer quality designs and the best project management for <br>your ideas, 100% delivery guaranteed. See for yourself, get on board';
echo '';
echo '</div>';
echo '<!-- layer nr. 3 -->';
echo '<div class="tp-caption z-index-5"';
echo 'data-x="['right','right','right','right']" data-hoffset="['45','45','20','15']"';
echo 'data-y="['middle','middle','middle','middle']" data-voffset="['135','135','135','135']"';
echo 'data-fontsize="['18','18','18','18']"';
echo 'data-lineheight="['18','18','18','18']"';
echo 'data-width="none"';
echo 'data-height="none"';
echo 'data-whitespace="nowrap"';
echo 'data-type="text"';
echo 'data-responsive_offset="on"';
echo 'data-frames='[{"from":"y:50px;opacity:0;","speed":1000,"to":"o:1;","delay":1000,"ease":"Power4.easeInOut"},{"delay":"wait","speed":1000,"to":"y:[175%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"Power2.easeInOut"},{"frame":"hover","speed":"300","ease":"Power1.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);bw:2px 2px 2px 2px;"}]'';
echo 'data-textAlign="['center','center','center','center']"';
echo 'style="z-index: 7; white-space: nowrap; font-family:'Poppins', sans-serif; !important; font-weight: 100;">';
echo '<a href="#." class="btn btn-gradient btn-rounded btn-large mr-2">Get Started</a>';
echo '<a href="#." class="btn btn btn-white btn-rounded btn-large">learn More</a>';
echo '</div>';
echo '';
echo '';
echo '</li>';
echo '';
echo '';
echo '</ul>';
echo '</div>';
echo '<!-- END REVOLUTION SLIDER -->';
echo '</div>';
echo '';
echo '<!--slider social-->';
echo '<div class="slider-social">';
echo '<ul class="list-unstyled">';
echo '<li><a class="facebook-text-hvr" href="javascript:void(0);"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>';
echo '<li><a class="twitter-text-hvr" href="javascript:void(0);"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>';
echo '<li><a class="linkedin-text-hvr" href="javascript:void(0);"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>';
echo '<li><a class="instagram-text-hvr" href="javascript:void(0);"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '';
echo '<!--scroll down-->';
echo '<a href="#about" class="scroll-down scroll">Scroll Down <i class="fa fa-long-arrow-alt-down"></i></a>';
echo '';
echo '</section>';
echo '<!--slider end-->';
echo '';
echo '<!--About Start-->';
echo '<section id="about">';
echo '<div class="container">';
echo '<!--About-->';
echo '<div class="row align-items-center wow fadeIn">';
echo '<div class="col-md-6">';
echo '<div class="title">';
echo '<h6 class="third-color mb-3">Basic info about me</h6>';
echo '<h2>J.D.G Creative Design Agency in Lagos, Nigeria</h2>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 mb-4">';
echo '<p>After nearly a decade working for top design firms in the industry, I now focus all of my time on helping clients of my own. Whether you’re looking to redesign your website or just need help with user experience; need printed materials like business cards, brochures, or posters; are undertaking a logo or identity rework; even if you’re just working on a Powerpoint presentation—I’m here to help.';
echo '</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!--Features-->';
echo '<div class="row">';
echo '<div class="col-md-4 wow fadeInLeft">';
echo '<div class="feature-box">';
echo '<span class="item-number gradient-text1">';
echo '01.';
echo '</span>';
echo '<h6 class="mb-4">Website Design</h6>';
echo '<p>I offer creative web designing for various templates and live websites. Also available for Mobile App UI designing.</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4 wow fadeInUp">';
echo '<div class="feature-box">';
echo '<span class="item-number gradient-text1">';
echo '02.';
echo '</span>';
echo '<h6 class="mb-4">Photography</h6>';
echo '<p>I specialise in Photography ranging from, Lifestyle, Portraits to Brands. If you would like to have any of your products photographed please do get in touch.</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4 wow fadeInRight">';
echo '<div class="feature-box">';
echo '<span class="item-number gradient-text1">';
echo '03.';
echo '</span>';
echo '<h6 class="mb-4">Graphics Design</h6>';
echo '<p> I'm an Expert Graphic Designer and can do a fantastic job by your request! I will design outstanding graphics for your business and personal use.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</section>';
echo '<!--About End-->';
echo '';
echo '<!--Team Start-->';
echo '';
echo '<!--Team Start-->';
echo '';
echo '<!--Portfolio Start-->';
echo '<section id="portfolio" class="cube-portfolio1">';
echo '<div class="container">';
echo '<!--About-->';
echo '<div class="row align-items-center">';
echo '<div class="col-md-6 wow fadeInLeft">';
echo '<div class="title">';
echo '<h6 class="third-color mb-3">Latest designs by yours truly</h6>';
echo '<h2>Creative Portfolio Designs</h2>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 mb-4 wow fadeInRight">';
echo '<p>I'm a Lifestyle Photographer/Designer experienced with Brand Promo and Product Content. I have worked with several brands, mainly Nigeria and US based that showcase new products. I have models to the ready depending on your requirements. Here are some of my works.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row wow fadeInUp">';
echo '<div class="col-md-12">';
echo '';
echo '<!--Portfolio Filters-->';
echo '<div id="js-filters-mosaic-flat" class="cbp-l-filters-button">';
echo '';
echo '<div data-filter="*" class="cbp-filter-item-active cbp-filter-item">All</div>';
echo '<span class="text-blue">/</span>';
echo '<div data-filter=".graphic" class="cbp-filter-item">Graphic Design</div>';
echo '<span class="text-blue"> / </span>';
echo '<div data-filter=".web-design" class="cbp-filter-item">Web design</div>';
echo '<span class="text-blue"> / </span>';
echo '<div data-filter=".graphic" class="cbp-filter-item">Photography</div>';
echo '<span class="text-blue"> / </span>';
echo '<div data-filter=".marketing" class="cbp-filter-item">Marketing</div>';
echo '</div>';
echo '';
echo '<!--Portfolio Items-->';
echo '<div id="js-grid-mosaic-flat" class="cbp cbp-l-grid-mosaic-flat">';
echo '';
echo '<div class="cbp-item web-design graphic">';
echo '<a href="img/AFRIQ_relax.jpg" class="cbp-caption cbp-lightbox">';
echo '<div class="cbp-caption-defaultWrap">';
echo '<img src="images/art1.jpg" alt="port-1">';
echo '</div>';
echo '<div class="cbp-caption-activeWrap"></div>';
echo '<div class="cbp-l-caption-alignCenter center-block">';
echo '<div class="cbp-l-caption-body">';
echo '<div class="plus"></div>';
echo '<h5 class="text-white mb-1">Latest Work</h5>';
echo '<p class="text-white">See Our Amazing Work</p>';
echo '</div>';
echo '</div>';
echo '';
echo '</a>';
echo '</div>';
echo '<div class="cbp-item seo marketing">';
echo '<a href="img/african-beauty.jpg" class="cbp-caption cbp-lightbox">';
echo '<div class="cbp-caption-defaultWrap">';
echo '<img src="images/art2.jpg" alt="port-2">';
echo '</div>';
echo '<div class="cbp-caption-activeWrap"></div>';
echo '<div class="cbp-l-caption-alignCenter center-block">';
echo '<div class="cbp-l-caption-body">';
echo '<div class="plus"></div>';
echo '<h5 class="text-white mb-1">Latest Work</h5>';
echo '<p class="text-white">See Our Amazing Work</p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="cbp-item seo marketing">';
echo '<a href="img/AFRIQQA_jdg.jpg" class="cbp-caption cbp-lightbox">';
echo '<div class="cbp-caption-defaultWrap">';
echo '<img src="images/art4.jpg" alt="port-4">';
echo '</div>';
echo '<div class="cbp-caption-activeWrap"></div>';
echo '<div class="cbp-l-caption-alignCenter center-block">';
echo '<div class="cbp-l-caption-body">';
echo '<div class="plus"></div>';
echo '<h5 class="text-white mb-1">Latest Work</h5>';
echo '<p class="text-white">See Our Amazing Work</p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="cbp-item graphic seo marketing">';
echo '<a href="img/AFRIQ-series_NIKE.jpg" class="cbp-caption cbp-lightbox">';
echo '<div class="cbp-caption-defaultWrap">';
echo '<img src="images/art5.jpg" alt="port-3">';
echo '</div>';
echo '<div class="cbp-caption-activeWrap"></div>';
echo '<div class="cbp-l-caption-alignCenter center-block">';
echo '<div class="cbp-l-caption-body">';
echo '<div class="plus"></div>';
echo '<h5 class="text-white mb-1">Latest Work</h5>';
echo '<p class="text-white">See Our Amazing Work</p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="cbp-item seo marketing graphic ">';
echo '<a href="img/face-flowervasejdg.jpg" class="cbp-caption cbp-lightbox">';
echo '<div class="cbp-caption-defaultWrap">';
echo '<img src="images/art7.jpg" alt="port-6">';
echo '</div>';
echo '<div class="cbp-caption-activeWrap"></div>';
echo '<div class="cbp-l-caption-alignCenter center-block">';
echo '<div class="cbp-l-caption-body">';
echo '<div class="plus"></div>';
echo '<h5 class="text-white mb-1">Latest Work</h5>';
echo '<p class="text-white">See Our Amazing Work</p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="cbp-item web-design seo">';
echo '<a href="img/feel-fly.jpg" class="cbp-caption cbp-lightbox">';
echo '<div class="cbp-caption-defaultWrap">';
echo '<img src="images/art8.jpg" alt="port-7">';
echo '</div>';
echo '<div class="cbp-caption-activeWrap"></div>';
echo '<div class="cbp-l-caption-alignCenter center-block">';
echo '<div class="cbp-l-caption-body">';
echo '<div class="plus"></div>';
echo '<h5 class="text-white mb-1">Latest Work</h5>';
echo '<p class="text-white">See Our Amazing Work</p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="cbp-item web-design graphic">';
echo '<a href="img/feel-good.jpg" class="cbp-caption cbp-lightbox">';
echo '<div class="cbp-caption-defaultWrap">';
echo '<img src="images/art9.jpg" alt="port-8">';
echo '</div>';
echo '<div class="cbp-caption-activeWrap"></div>';
echo '<div class="cbp-l-caption-alignCenter center-block">';
echo '<div class="cbp-l-caption-body">';
echo '<div class="plus"></div>';
echo '<h5 class="text-white mb-1">Latest Work</h5>';
echo '<p class="text-white">See Our Amazing Work</p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="cbp-item web-design graphic">';
echo '<a href="img/marsaiMARTINS" class="cbp-caption cbp-lightbox">';
echo '<div class="cbp-caption-defaultWrap">';
echo '<img src="images/art12.jpg" alt="port-8">';
echo '</div>';
echo '<div class="cbp-caption-activeWrap"></div>';
echo '<div class="cbp-l-caption-alignCenter center-block">';
echo '<div class="cbp-l-caption-body">';
echo '<div class="plus"></div>';
echo '<h5 class="text-white mb-1">Latest Work</h5>';
echo '<p class="text-white">See Our Amazing Work</p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="cbp-item web-design graphic">';
echo '<a href="img/icebud.jpg" class="cbp-caption cbp-lightbox">';
echo '<div class="cbp-caption-defaultWrap">';
echo '<img src="images/art10.jpg" alt="port-8">';
echo '</div>';
echo '<div class="cbp-caption-activeWrap"></div>';
echo '<div class="cbp-l-caption-alignCenter center-block">';
echo '<div class="cbp-l-caption-body">';
echo '<div class="plus"></div>';
echo '<h5 class="text-white mb-1">Latest Work</h5>';
echo '<p class="text-white">See Our Amazing Work</p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="cbp-item web-design graphic">';
echo '<a href="img/dove-collage.jpg" class="cbp-caption cbp-lightbox">';
echo '<div class="cbp-caption-defaultWrap">';
echo '<img src="images/art6.jpg" alt="port-5">';
echo '</div>';
echo '<div class="cbp-caption-activeWrap"></div>';
echo '<div class="cbp-l-caption-alignCenter center-block">';
echo '<div class="cbp-l-caption-body">';
echo '<div class="plus"></div>';
echo '<h5 class="text-white mb-1">Latest Work</h5>';
echo '<p class="text-white">See Our Amazing Work</p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '<!--To Enable Load More Button Remove The Class="d-none"-->';
echo '<div id="js-loadMore-mosaic-flat" class="cbp-l-loadMore-bgbutton d-none">';
echo '<a href="loadmore.html" class="cbp-l-loadMore-link no-transition btn-rounded" rel="nofollow">';
echo '<span class="cbp-l-loadMore-defaultText no-transition ">Load More</span>';
echo '<span class="cbp-l-loadMore-loadingText ">Loading...</span>';
echo '<span class="cbp-l-loadMore-noMoreLoading">Finish</span>';
echo '</a>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</section>';
echo '<!--Portfolio end-->';
echo '';
echo '<!--Pricing Start-->';
echo '';
echo '<!--Pricing End Start-->';
echo '';
echo '<!--Content Start-->';
echo '<section class="content">';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '<div class="col-lg-6 wow fadeInLeft">';
echo '<div class="title">';
echo '<h6 class="third-color mb-3">You can trust me</h6>';
echo '<h2 class="mb-4">I Can<br>Make Your Design</h2>';
echo '<p>Let me know if you would like anything customised, that can be arranged.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-6 wow fadeInRight">';
echo '<div class="content-image">';
echo '<img src="images/phone.png" alt="image">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!--Content End-->';
echo '';
echo '<!--Testimonial Start-->';
echo '<section class="p-0">';
echo '<div class="container-fluid">';
echo '<div class="row">';
echo '<!--testimonial-->';
echo '<div class="col-md-6 bg-light">';
echo '<div id="testimonial_slider" class="owl-carousel">';
echo '<!--testimonial item-->';
echo '<div class="testimonial-item item">';
echo '<i class="fa fa-quote-right testimonial-icon gradient-text1"></i>';
echo '<p class="mb-4">JerryDigiGraphixs really helped me with my work and i am glad i went for him. </p>';
echo '';
echo '<!--Image-->';
echo '<div class="testimonial-image">';
echo '<img src="images/t1.png" alt="image">';
echo '</div>';
echo '<h5 class="font-weight-500 third-color">Sara T.</h5>';
echo '<span class="destination">Project Manager, S. Studio</span>';
echo '</div>';
echo '<!--testimonial item-->';
echo '<div class="testimonial-item item">';
echo '<i class="fa fa-quote-right testimonial-icon gradient-text1"></i>';
echo '<p class="mb-4">This guy is amazing with the colors and creative concepts. Really appreciate your work and efforts. </p>';
echo '';
echo '<!--Image-->';
echo '<div class="testimonial-image">';
echo '<img src="images/t3.png" alt="image">';
echo '</div>';
echo '<h5 class="font-weight-500 third-color">Jayseph Ace</h5>';
echo '<span class="destination">Company CEO, AceNetics.</span>';
echo '</div>';
echo '<!--testimonial item-->';
echo '<div class="testimonial-item item">';
echo '<i class="fa fa-quote-right testimonial-icon gradient-text1"></i>';
echo '<p class="mb-4">Really quality stuff from this guy. Was skeptical at first but he really came through for me and my team. </p>';
echo '';
echo '<!--Image-->';
echo '<div class="testimonial-image">';
echo '<img src="images/t2.png" alt="image">';
echo '</div>';
echo '<h5 class="font-weight-500 third-color">Torinto J. Cyrus</h5>';
echo '<span class="destination">CEO, Torinto Inc.</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!--counters-->';
echo '<div class="col-md-6 p-0">';
echo '<!--counter background-->';
echo '<div class="counters d-flex align-items-center text-left bg-img1">';
echo '<!--overlay-->';
echo '<div class="bg-overlay gradient-bg1 opacity-8"></div>';
echo '<div class="counter-row">';
echo '<!--counters item-->';
echo '<div class="counter-item">';
echo '<div class="count alt-font">6</div>';
echo '<h6 class="text-white">Years of Experience</h6>';
echo '</div>';
echo '<!--counters item-->';
echo '<div class="counter-item">';
echo '<div class="count alt-font">280</div>';
echo '<h6 class="text-white">Photographs Taken</h6>';
echo '</div>';
echo '<!--counters item-->';
echo '<div class="counter-item">';
echo '<div class="count alt-font">456</div>';
echo '<h6 class="text-white">Happy Clients</h6>';
echo '</div>';
echo '<!--counters item-->';
echo '<div class="counter-item">';
echo '<div class="count alt-font">479</div>';
echo '<h6 class="text-white">Finished Projects</h6>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!--Testimonial End-->';
echo '';
echo '<!--App Section-->';
echo '<section>';
echo '<div class="container">';
echo '<!--Heading-->';
echo '<div class="row">';
echo '<div class="col-md-12 text-center wow fadeIn">';
echo '<div class="title d-inline-block">';
echo '<h6 class="mb-3">Most reliable application designing</h6>';
echo '<h2 class="gradient-text1 mb-3">Mobile App Design</h2>';
echo '<p>I design creative and beautiful mobile app UI interfaces. From a concept or from idea. </p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!--App deatil-->';
echo '<div class="row align-items-center text-center">';
echo '';
echo '<div class="col-md-4 wow fadeInLeft">';
echo '<!--App deatil item-->';
echo '<div class="app-feature">';
echo '<i class="fa fa-eye gradient-text1" aria-hidden="true"></i>';
echo '<h4 class="mb-3">Personal Projects</h4>';
echo '<p>I can design an intuitive UI for your personal mobile app.</p>';
echo '</div>';
echo '<!--App deatil item-->';
echo '<div class="app-feature">';
echo '<i class="fa fa-edit gradient-text1" aria-hidden="true"></i>';
echo '<h4 class="mb-3">Customization</h4>';
echo '<p>Looking to beautify your already made UI? I can make smooth and amazing customixations.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!--app slider-->';
echo '<div class="col-md-4 wow fadeInUp">';
echo '<!--app Image-->';
echo '<div class="app-image">';
echo '<img src="images/iphone-img.png" alt="image">';
echo '<div id="app-slider" class="owl-carousel owl-theme">';
echo '<div class="item">';
echo '<img src="images/iphone-slide1.jpg" alt="">';
echo '</div>';
echo '<div class="item">';
echo '<img src="images/iphone-slide2.jpg" alt="">';
echo '</div>';
echo '<div class="item">';
echo '<img src="images/iphone-slide3.jpg" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-4 wow fadeInRight">';
echo '<!--App deatil item-->';
echo '<div class="app-feature">';
echo '<i class="fa fa-code gradient-text1" aria-hidden="true"></i>';
echo '<h4 class="mb-3">Powerful Code</h4>';
echo '<p>A partner Organization "AceNetics" can help you develop your website or mobile app from scratch.</p>';
echo '</div>';
echo '<!--App deatil item-->';
echo '<div class="app-feature">';
echo '<i class="fa fa-folder-open gradient-text1" aria-hidden="true"></i>';
echo '<h4 class="mb-3">Documentation</h4>';
echo '<p>My products come with documentations to help you better implement or further customize the design.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</section>';
echo '<!--App Section End-->';
echo '';
echo '<!--Blog Start-->';
echo '';
echo '<!--Blog End-->';
echo '';
echo '<!--Address Start-->';
echo '';
echo '<section id="contact" class="p-0">';
echo '<div class="container-fluid">';
echo '<div class="row align-items-center">';
echo '<div class="col-md-6 p-0">';
echo '<div class="address-box title mb-0 bg-img4">';
echo '<!--overlay-->';
echo '<div class="bg-overlay gradient-bg1 opacity-15"></div>';
echo '<div class="address-text text-center text-white position-relative wow fadeInUp">';
echo '<h6 class="mb-3">You can contact me 24/7 on any of these</h6>';
echo '<!--title-->';
echo '<h2 class="mb-4">JerryDigiGraphixs Agency, Lagos</h2>';
echo '<!--Address-->';
echo '<p class="mb-3 text-white">Lagos, Nigeria. </p>';
echo '<!--Phone-->';
echo '<p class="mb-3 text-white">Office Telephone : +234 708 992 1915<br>';
echo 'Mobile : +234 708 992 1915 </p>';
echo '<!--Email-->';
echo '<p class="mb-3 text-white">Email : Jdgcr8ive@gmail.com<br>';
echo 'Inquiries : Jdgcr8ive@gmail.com</p>';
echo '<!--Timing-->';
echo '<p class="mb-3 text-white">Mon-Sat: 6am to 7am</p>';
echo '<!--Social Icon-->';
echo '<div class="address-social">';
echo '<ul class="list-unstyled">';
echo '<li><a class="facebook-text-hvr" href="https://facebook.com/"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>';
echo '<li><a class="twitter-text-hvr" href="https://twitter.com/"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>';
echo '<!-- <li><a class="google-text-hvr" href="javascript:void(0);"><i class="fab fa-google-plus" aria-hidden="true"></i></a></li> -->';
echo '<!-- <li><a class="linkedin-text-hvr" href="javascript:void(0);"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li> -->';
echo '<li><a class="instagram-text-hvr" href="https://instagram.com/"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-6 p-0">';
echo '<div id="maps"  >';
echo '<div class="address-box title mb-0 bg-img4">';
echo '<!--overlay-->';
echo '<div class="bg-overlay gradient-bg1 opacity-8"></div>';
echo '<div class="address-text text-center text-white position-relative wow fadeInUp">';
echo '<h6 class="mb-3">Contact Our Partners on Web and Mobile Development</h6>';
echo '<!--title-->';
echo '<h2 class="mb-4">AceNetics Core Evolution, Lagos</h2>';
echo '<!--Address-->';
echo '<p class="mb-3 text-white">Lagos, Nigeria. </p>';
echo '<!--Phone-->';
echo '<p class="mb-3 text-white">Office Telephone : +234 813 921 5502<br>';
echo 'Mobile : +234 813 921 5502 </p>';
echo '<!--Email-->';
echo '<p class="mb-3 text-white">mail : acenetvx@gmail.com<br>';
echo 'Inquiries : acenetvx@gmail.com</p>';
echo '<!--Timing-->';
echo '<p class="mb-3 text-white">Mon-Sunday: 6am to 6am</p>';
echo '<!--Social Icon-->';
echo '<div class="address-social">';
echo '<ul class="list-unstyled">';
echo '<li><a class="facebook-text-hvr" href="https://facebook.com/acenetics"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>';
echo '<li><a class="twitter-text-hvr" href="https://twitter.com/acenetics"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>';
echo '<!-- <li><a class="google-text-hvr" href="javascript:void(0);"><i class="fab fa-google-plus" aria-hidden="true"></i></a></li> -->';
echo '<!-- <li><a class="linkedin-text-hvr" href="javascript:void(0);"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li> -->';
echo '<li><a class="instagram-text-hvr" href="https://instagram.com/acenetics"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!--Address End-->';
echo '';
echo '<!--Contact Start-->';
echo '';
echo '<!--Contact End-->';
echo '';
echo '<!--Footer Start-->';
echo '<section class="bg-light text-center">';
echo '<h2 class="d-none">hidden</h2>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-md-12">';
echo '<div class="footer-social">';
echo '<ul class="list-unstyled">';
echo '<li><a class="wow fadeInUp" href="https://facebook.com/"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>';
echo '<li><a class="wow fadeInDown" href="https://twitter.com/"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>';
echo '<!-- <li><a class="wow fadeInUp" href="javascript:void(0);"><i class="fab fa-google-plus" aria-hidden="true"></i></a></li> -->';
echo '<!-- <li><a class="wow fadeInDown" href="javascript:void(0);"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li> -->';
echo '<li><a class="wow fadeInUp" href="https://instagram.com/"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>';
echo '<!-- <li><a class="wow fadeInDown" href="javascript:void(0);"><i class="fab fa-envelope-o" aria-hidden="true"></i></a></li> -->';
echo '</ul>';
echo '</div>';
echo '<p class="company-about fadeIn">© 2020 JerryDigiGraphixs. Crafted With 🖤 By <a href="https://styrix.info/">AceNetics</a></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!--Footer End-->';
echo '';
echo '<!--Scroll Top-->';
echo '<a class="scroll-top-arrow" href="javascript:void(0);"><i class="fa fa-angle-up"></i></a>';
echo '<!--Scroll Top End-->';
echo '';
echo '';
echo '';
echo '<!-- Optional JavaScript -->';
echo '<script src="js/jquery-3.3.1.min.js"></script>';
echo '<script src="js/popper.min.js"></script>';
echo '<script src="js/bootstrap.min.js"></script>';
echo '<script src="js/jquery.appear.js"></script>';
echo '<!-- isotop gallery -->';
echo '<script src="js/isotope.pkgd.min.js"></script>';
echo '<!-- cube portfolio gallery -->';
echo '<script src="js/jquery.cubeportfolio.min.js"></script>';
echo '<!-- owl carousel slider -->';
echo '<script src="js/owl.carousel.min.js"></script>';
echo '<!-- text rotate -->';
echo '<script src="js/morphext.min.js"></script>';
echo '<!-- particles -->';
echo '<script src="js/particles.min.js"></script>';
echo '<!-- parallax Background -->';
echo '<script src="js/parallaxie.min.js"></script>';
echo '<!-- fancybox popup -->';
echo '<script src="js/jquery.fancybox.min.js"></script>';
echo '<!-- fancybox popup -->';
echo '<script src="js/wow.js"></script>';
echo '<!-- REVOLUTION JS FILES -->';
echo '<script src="rs-plugin/js/jquery.themepunch.tools.min.js"></script>';
echo '<script src="rs-plugin/js/jquery.themepunch.revolution.min.js"></script>';
echo '<!-- SLIDER REVOLUTION EXTENSIONS -->';
echo '<script src="rs-plugin/js/extensions/revolution.extension.actions.min.js"></script>';
echo '<script src="rs-plugin/js/extensions/revolution.extension.carousel.min.js"></script>';
echo '<script src="rs-plugin/js/extensions/revolution.extension.kenburn.min.js"></script>';
echo '<script src="rs-plugin/js/extensions/revolution.extension.layeranimation.min.js"></script>';
echo '<script src="rs-plugin/js/extensions/revolution.extension.migration.min.js"></script>';
echo '<script src="rs-plugin/js/extensions/revolution.extension.navigation.min.js"></script>';
echo '<script src="rs-plugin/js/extensions/revolution.extension.parallax.min.js"></script>';
echo '<script src="rs-plugin/js/extensions/revolution.extension.slideanims.min.js"></script>';
echo '<script src="rs-plugin/js/extensions/revolution.extension.video.min.js"></script>';
echo '<!-- map -->';
echo '<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAhrdEzlfpnsnfq4MgU1e1CCsrvVx2d59s"></script>';
echo '<script src="js/map.js"></script>';
echo '<!-- custom script -->';
echo '<script src="js/script.js"></script>';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>